// <auto-generated />
namespace DiveO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhotoList_Virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotoList_Virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201512281753050_PhotoList_Virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
