// <auto-generated />
namespace DiveO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MapPoint_AddedTo_Dive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapPoint_AddedTo_Dive));
        
        string IMigrationMetadata.Id
        {
            get { return "201606052116290_MapPoint_AddedTo_Dive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
